/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-pouchdb-query.html
 */

/// <reference path="../polymer/types/polymer.d.ts" />
/// <reference path="app-pouchdb-database-behavior.d.ts" />
/// <reference path="pouchdb.d.ts" />
/// <reference path="pouchdb.find.d.ts" />

/**
 * `app-pouchdb-query` allows for declarative, read-only querying into a PouchDB
 * database. The semantics for querying match those of the
 * [pouchdb-find plugin](https://github.com/nolanlawson/pouchdb-find).
 *
 * In order to create an `app-pouchdb-query` against any field other than `_id`, at
 * least one index needs to have been created in your PouchDB database. You can use
 * `app-pouchdb-index` to do this declaratively. For example:
 *
 * ```html
 * <app-pouchdb-index
 *     db-name="cats"
 *     fields='["name"]'>
 * </app-pouchdb-index>
 * <app-pouchdb-query
 *     db-name="cats"
 *     selector="name $exists true"
 *     fields='["_id","name"]'
 *     sort='["name"]'
 *     data="{{cats}}">
 * </app-pouchdb-query>
 * ```
 *
 * In the above example, an index is created on the "name" field of the "cats"
 * database. This allows the query to select by the "name" field, and sort by the
 * "name" field.
 *
 * By default, PouchDB creates an index on the "_id" field, so if you don't
 * particularly care about sorting or selecting on other fields, you don't need to
 * create any extra indexes.
 *
 * ## Describing selectors
 *
 * This element requires a specialized selector syntax that maps to the semantics
 * of the pouchdb-find plugin. For example, if you wish to create the following
 * selector:
 *
 * ```javascript
 * {
 *   series: 'Mario',
 *   debut: { $gt: 1990 }
 * }
 * ```
 *
 * You should format the `selector` property this way:
 *
 * ```javascript
 * "series $eq 'Mario', debut $gt 1990"
 * ```
 *
 * This makes selectors more convenient to write declaratively, while still
 * maintaining the ability to express selectors with full fidelity. For more
 * documentation on pouchdb-find selectors, please check out the docs
 * [here](https://github.com/nolanlawson/pouchdb-find#dbfindrequest--callback).
 */
interface AppPouchdbQueryElement extends Polymer.Element, Polymer.AppPouchDBDatabaseBehavior {

  /**
   * The selector to use when querying for documents. Fields referenced
   * in the selector must have indexes created for them.
   */
  selector: string|null|undefined;

  /**
   * The fields to include in the returned documents.
   */
  fields: any[]|null|undefined;

  /**
   * A list of field names to sort by. Fields in this list must have
   * indexes created for them.
   */
  sort: any[]|null|undefined;

  /**
   * The maximum number of documents that can be returned. The default (0)
   * specifies no limit.
   */
  limit: number|null|undefined;

  /**
   * The number of documents to skip before returning results that match
   * the query. In other words, the offset from the beginning of the
   * of the result set to start at.
   */
  skip: number|null|undefined;

  /**
   * An object representing the parsed form of the selector, mapping to
   * a valid selector value as described in
   * [the pouchdb-find docs](https://github.com/nolanlawson/pouchdb-find).
   */
  readonly parsedSelector: object|null|undefined;

  /**
   * A configuration object suitable to be passed to the `find` method of
   * the PouchDB database. For more information, refer to the docs
   * [here](https://github.com/nolanlawson/pouchdb-find/blob/master/README.md#dbfindrequest--callback)
   */
  readonly query: object|null|undefined;

  /**
   * The results of the query, if any.
   */
  readonly data: any[]|null|undefined;

  /**
   * PouchDB only notifies of additive changes to the result set of a query.
   * In order to keep the query results up to date with other types of
   * changes, this method can be called to perform the query again without
   * changing any of this element's other properties.
   */
  refresh(): void;
}

interface HTMLElementTagNameMap {
  "app-pouchdb-query": AppPouchdbQueryElement;
}
