/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-pouchdb-sync.html
 */

/// <reference path="../polymer/types/polymer.d.ts" />
/// <reference path="pouchdb.d.ts" />

/**
 * `app-pouchdb-sync` arranges for one-directional or bi-directional
 * synchronization between two PouchDB databases. For one-directional
 * synchronization, it forwards to `PouchDB.replicate`, and for bi-directional
 * synchronization, it forwards to `PouchDB.sync`.
 *
 * Here is an example of bi-directional synchronization between a local database
 * and a remote one:
 *
 * ```html
 * <app-pouchdb-sync
 *     src="cats"
 *     target="https://example.com:5678/cats"
 *     bidirectional>
 * </app-pouchdb-sync>
 * ```
 *
 * For more information on PouchDB synchronization topics, please refer to the
 * documentation [here](https://pouchdb.com/guides/replication.html).
 */
interface AppPouchdbSyncElement extends Polymer.Element {

  /**
   * The source to sync from. If this sync is `bidirectional`, then the
   * `src` and `target` values are interchangeable.
   */
  src: string|null|undefined;

  /**
   * The `target` to sync to. If this sync is `bidirectional`, then the
   * `src` and `target` values are interchangeable.
   */
  target: string|null|undefined;

  /**
   * While `false`, synchronization will only happen from the `src` to the
   * `target`. One-directional synchronization follows the semantics of
   * `PouchDB.replicate`. Set to `true` to make the sync bidirectional,
   * which uses `PouchDB.sync` instead.
   */
  bidirectional: boolean|null|undefined;

  /**
   * An event emitter that notifies of events in the synchronization
   * process.
   */
  readonly sync: object|null|undefined;

  /**
   * Set to true to log change events that are emitted by the `sync`
   * instance.
   */
  log: boolean|null|undefined;
}

interface HTMLElementTagNameMap {
  "app-pouchdb-sync": AppPouchdbSyncElement;
}
