/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   pouchdb.find.html
 */

/// <reference path="../pouchdb-find/dist/pouchdb.find.d.ts" />

